new writeup for beginners
USTC-Hackergame/hackergame2020-writeups pull request #22
Opened 2020-11-07 10:20 UTC by PB18061383

2020-11-07 11:21 UTC, makeding commented
我觉得弄成 markdown 更好点？
参考 [这个](https://guides.github.com/features/mastering-markdown/) 链接学习一下。

2020-11-07 13:32 UTC, taoky requested changes
请将自己的 writeup 放置在 `players/你的昵称` 格式的文件夹下。

2020-11-08 08:40 UTC, VergeDX commented
@PB18061383

2020-11-19 06:21 UTC, taoky commented
#47

2020-11-19 06:21 UTC, closed without merging